---
- name: "3.2.1 | PATCH | Ensure 'Enable Google Cast' is set to 'Disabled'"
  when:
    - chrome_cis_level_1
    - chrome_cis_rule_3_2_1
  tags:
    - level1
    - automated
    - patch
    - rule_3.2.1
    - google_cast
  ansible.builtin.set_fact:
    chrome_cis_policies: "{{ chrome_cis_policies | combine({'EnableMediaRouter': false}) }}"
