---
- name: "1.1.1 | PATCH | Ensure 'Cross-origin HTTP Authentication prompts' is set to 'Disabled'"
  when:
    - chrome_cis_level_1
    - chrome_cis_rule_1_1_1
  tags:
    - level1
    - automated
    - patch
    - rule_1.1.1
    - http_auth
  ansible.builtin.set_fact:
    chrome_cis_policies: "{{ chrome_cis_policies | combine({'AllowCrossOriginAuthPrompt': false}) }}"
